In [1]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [3]:
import pandas as pd
import numpy as np

In [4]:
COLAB_FILEPATH = './drive/My Drive/Shopee Code League -Address Elements Extraction/'

In [6]:
data = pd.read_csv(COLAB_FILEPATH+'test.csv')

In [7]:
data.head()

   id                                    raw_address
0   0          s. par 53 sidanegara 4 cilacap tengah
1   1          angg per, baloi indah kel. lubuk baja
2   2                          asma laun, mand imog,
3   3  ud agung rej, raya nga sri wedari karanganyar
4   4                     cut mutia, 35 baiturrahman

In [8]:
submission = pd.DataFrame({
    'id':data['id'],
    'POI/street':'/'
    })
submission

          id POI/street
0          0          /
1          1          /
2          2          /
3          3          /
4          4          /
...      ...        ...
49995  49995          /
49996  49996          /
49997  49997          /
49998  49998          /
49999  49999          /

[50000 rows x 2 columns]

In [11]:
submission.to_csv(COLAB_FILEPATH+'submission_failed.csv', header=True, index=False)